[package]
name = "hello_graphics"
version = "0.1.0"
authors = ["Vishal Sodani <vishalsodani@rediffmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
